name: Deploy to InfinityFree

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install lftp
        run: sudo apt-get update -y && sudo apt-get install -y lftp

      - name: Configure LFTP
        run: |
          echo "machine ${{ secrets.FTP_SERVER }} login ${{ secrets.FTP_USERNAME }} password ${{ secrets.FTP_PASSWORD }}" > ~/.netrc
          chmod 600 ~/.netrc
          mkdir -p ~/.lftp
          echo "set ssl:verify-certificate no" >> ~/.lftp/rc
          echo "set ftp:ssl-force true" >> ~/.lftp/rc

      - name: Deploy via FTPS
        run: |
          lftp -e "mirror --reverse --delete --verbose ./ /htdocs/; quit" ${{ secrets.FTP_SERVER }}
